### ISSUE TITLE
should return all numbers if there's a valid one not just the valid numbers

### ISSUE THREAD

**Issue by ilorez** [Allobaba-WebScrapy/Pages-Jaunes#2]
https://github.com/Allobaba-WebScrapy/Pages-Jaunes/blob/7f2a9fcd80da2b5e19b4a87265bbe363122e3dbe/scrape.py#L113

**Comment by Abdo-Nsila** [comment]
Now the Function return all numbers, when one of them is valide, also the `All` option is added.
### Tnx for your note
